name: job_mcq
description: "A new Flutter project."


publish_to: 'none'













version: 1.0.0+1

environment:
  sdk: ^3.6.2







dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.8
  firebase_auth: ^5.5.0
  cloud_firestore: ^5.6.4
  audioplayers: ^6.2.0
  vibration: ^3.1.3
  flutter_localizations:
    sdk: flutter
  shared_preferences: ^2.5.2
  in_app_purchase: ^3.2.1
  flutter_animate: ^4.5.2
  avatar_glow: ^3.0.1
  confetti: ^0.8.0
  flutter_gen: ^5.9.0
  intl_utils: ^2.8.10
  firebase_core: ^3.12.0
  provider: ^6.1.2
  firebase_analytics: ^11.4.4
  share_plus: ^10.1.4
  flutter_riverpod: ^2.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter






  flutter_lints: ^5.0.0





flutter:
  assets:
    - assets/bcs_questions.json
    - assets/ntrca_questions.json
    - assets/primary_questions.json
    - assets/bcs_10_questions.json
    - assets/bcs_2_questions.json
    - assets/bcs_3_questions.json
    - assets/ntrca_1_questions.json
    - assets/ntrca_2_questions.json
    - assets/ntrca_3_questions.json
    - assets/primary_1_questions.json
    - assets/primary_2_questions.json
    - assets/primary_3_questions.json


  uses-material-design: true

