name: job_mcq
description: "A new Flutter project."


publish_to: 'none'













version: 1.0.0+1

environment:
  sdk: ^3.6.2







dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.8
  firebase_auth: ^5.5.0
  cloud_firestore: ^5.6.4
  audioplayers: ^6.2.0
  vibration: ^3.1.3
  flutter_localizations:
    sdk: flutter
  shared_preferences: ^2.5.2
  in_app_purchase: ^3.2.1
  flutter_animate: ^4.5.2
  avatar_glow: ^3.0.1
  confetti: ^0.8.0
  flutter_gen: ^5.9.0
  intl_utils: ^2.8.10
  firebase_core: ^3.12.0
  provider: ^6.1.2
  firebase_analytics: ^11.4.4
  share_plus: ^10.1.4
  flutter_riverpod: ^2.6.1
  fl_chart: ^0.70.2

dev_dependencies:
  flutter_test:
    sdk: flutter






  flutter_lints: ^5.0.0





flutter:
  assets:
    - assets/bcs_10_questions.json
    - assets/bcs_11_questions.json
    - assets/bcs_12_questions.json
    - assets/bcs_13_questions.json
    - assets/bcs_14_questions.json
    - assets/bcs_15_questions.json
    - assets/bcs_16_questions.json
    - assets/bcs_17_questions.json
    - assets/bcs_18_questions.json
    - assets/bcs_19_questions.json
    - assets/bcs_20_questions.json
    - assets/bcs_21_questions.json
    - assets/bcs_22_questions.json
    - assets/bcs_23_questions.json
    - assets/bcs_24_questions.json
    - assets/bcs_25_questions.json
    - assets/bcs_26_questions.json
    - assets/bcs_27_questions.json
    - assets/bcs_28_questions.json
    - assets/bcs_29_questions.json
    - assets/bcs_30_questions.json
    - assets/bcs_31_questions.json
    - assets/bcs_32_questions.json
    - assets/bcs_33_questions.json
    - assets/bcs_34_questions.json
    - assets/bcs_35_questions.json
    - assets/bcs_36_questions.json
    - assets/bcs_37_questions.json
    - assets/bcs_38_questions.json
    - assets/bcs_39_questions.json
    - assets/bcs_40_questions.json
    - assets/bcs_41_questions.json
    - assets/bcs_42_questions.json
    - assets/bcs_43_questions.json
    - assets/bcs_44_questions.json
    - assets/bcs_45_questions.json
    - assets/bcs_46_questions.json
    - assets/ntrca_1_questions.json
    - assets/ntrca_2_questions.json
    - assets/ntrca_3_questions.json
    - assets/primary_1_questions.json
    - assets/primary_2_questions.json
    - assets/primary_3_questions.json


  uses-material-design: true

